name: angular build and push
on:
  workflow_dispatch:
  push: 
    branches: default
    
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    #   with:
    #     node-version: '16'
    # - run: npm install
    # - run: npm run build
    #   if: success()
    # - run: echo "******************************************************"     
    # - run: git remote -v     
    
    - run: ls  -R $GITHUB_WORKSPACE
    - run: cd $GITHUB_WORKSPACE/ecommerce-app/ui
      if: success()
    - run: npm install
    - run: npm run build
    - run: pwd
